version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
    #command: npm run dev
    #command: sh -c "tail -f /dev/null"